### ISSUE TITLE
复现结果与论文不一致，请问是什么原因？

### ISSUE THREAD

**Issue by Allan-waker** [wang-liangzai/SSBN#2]
在lap14数据集上的实验，没有更改任何参数，为什么结果差了几个点？
![屏幕截图 2024-03-16 135857](https://github.com/wang-liangzai/SSBN/assets/64625837/2824bb98-b5a8-4e3c-89ba-b7486f16ff1f)
![屏幕截图 2024-03-16 140102](https://github.com/wang-liangzai/SSBN/assets/64625837/e78831e7-47e1-472c-9f1d-97fed9662f3f)

**Comment by wang-liangzai** [comment]
感谢您的提问，我们仔细观察了实验设置并对我们的方法重新进行了验证，可以达到论文中的实验结果。我认为针对lap14数据集，您可以通过尝试调整对实验效果影响非常明显的GCN的损失率、跨度长度和训练次数这三个参数，其余设置均与我上传的代码一致即可。
![c7aa9bb231dbb84dcb1923ab96d4062](https://github.com/wang-liangzai/SSBN/assets/72295134/534569db-2ffe-4ef4-83bf-d37f5d20eab5)

**Comment by wwyx88** [comment]
> 在lap14数据集上的实验，没有更改任何参数，为什么结果差了几个点？ ![屏幕截图 2024-03-16 135857](https://private-user-images.githubusercontent.com/64625837/313377579-2824bb98-b5a8-4e3c-89ba-b7486f16ff1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjA4MzMsIm5iZiI6MTcyNjgyMDUzMywicGF0aCI6Ii82NDYyNTgzNy8zMTMzNzc1NzktMjgyNGJiOTgtYjVhOC00ZTNjLTg5YmEtYjc0ODZmMTZmZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA4MjIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZGFiY2E3OTg4NDliMGViZGFmMjVjZTA5YjllNmRhZTBjMThkNGI5NmFhNzRjNjY2NTRmOWU5NTYxZGVmMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7I4pdwBmDAinD2BekcI9J7uARevm-Ea7rBujdLqYyYY) ![屏幕截图 2024-03-16 140102](https://private-user-images.githubusercontent.com/64625837/313377607-e78831e7-47e1-472c-9f1d-97fed9662f3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjA4MzMsIm5iZiI6MTcyNjgyMDUzMywicGF0aCI6Ii82NDYyNTgzNy8zMTMzNzc2MDctZTc4ODMxZTctNDdlMS00NzJjLTlmMWQtOTdmZWQ5NjYyZjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA4MjIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YzY4ODRlMjkwM2YyZDQ2ZWEzNmJiMDkzNWFkZWE2MGQ5MjNmMzk1ZGFkN2M0ZjcyZTY2ZDYwN2ViMDA5N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JXx2GeagnvsVys0vL4HPsVJEjP7iLCxMj820F9FqKYw)
请问一下您后来调参数能够调到论文跑的实验吗
