### ISSUE TITLE
关于本文的复现，loss怎么达到几万，而且复现的结果比你低十个点

### ISSUE THREAD

**Issue by wwyx88** [wang-liangzai/SSBN#3]
![实验结果](https://github.com/user-attachments/assets/b2342446-1d7d-4fa9-886b-05ff9b19fd8b)

**Comment by wang-liangzai** [comment]
感谢您的提问，首先是关于loss部分，我们在训练过程中直接将epoch中的loss全部加和之后再进行输出导致数值较大。其次我们之前仔细观察了实验设置并对我们的方法进行过重新验证，可以达到论文中的实验结果。我认为针对lap14数据集，您可以通过尝试调整对实验效果影响非常明显的GCN的损失率、跨度长度和训练次数这三个参数，其余设置均与我上传的代码一致即可。除此之外由于机器的不同，最终效果可能也会产生一定的上下浮动。
![8742f899eabe0bdc6eb829d8adfd28f](https://github.com/user-attachments/assets/5bb151a9-5e93-4097-a17e-6ab437ecb48d)

**Comment by wwyx88** [comment]
我能否加你一个联系方式，


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月3日(周二) 下午5:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wang-liangzai/SSBN] 关于本文的复现，loss怎么达到几万，而且复现的结果比你低十个点 (Issue #3)




 
感谢您的提问，首先是关于loss部分，我们在训练过程中直接将epoch中的loss全部加和之后再进行输出导致数值较大。其次我们之前仔细观察了实验设置并对我们的方法进行过重新验证，可以达到论文中的实验结果。我认为针对lap14数据集，您可以通过尝试调整对实验效果影响非常明显的GCN的损失率、跨度长度和训练次数这三个参数，其余设置均与我上传的代码一致即可。除此之外由于机器的不同，最终效果可能也会产生一定的上下浮动。
 8742f899eabe0bdc6eb829d8adfd28f.png (view on web)
 
&mdash;
